In [157]:
# import libraries
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix

In [158]:
#loading the dataset
df = pd.read_csv(r'C:\Users\Sanket M\OneDrive\Documents\Task List\ML\Diabetes_Prediction\Diabetes_prediction.csv')
df.head(10)

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
0            2  115.863387      56.410731      24.336736   94.385783   
1            2   92.490122      70.615520      23.443591  138.652426   
2            1   88.141469      63.262618      23.404364  149.358082   
3            2  108.453101      67.793632      20.751580  108.751638   
4            1  127.849443      94.725685      22.603078   25.269987   
5            2  108.870034      74.338518      25.390851   78.704740   
6            3   95.665270      54.157100      23.927648  130.989859   
7            0  108.353474      68.497370      22.611992  109.225691   
8            2  120.979399      50.617860      23.677139  -11.616854   
9            2  123.839177      75.067548      23.198216  181.809109   

         BMI  DiabetesPedigreeFunction        Age  Diagnosis  
0  26.455940                  0.272682  20.100494          0  
1  23.910167                  0.665160  44.912281          0  
2  21.948250                  0.676022  48.247873          1  
3  24.209304                  0.289636  42.749868          0  
4  32.997477                  0.601315  32.797789          0  
5  20.008180                  0.673117  24.893761          0  
6  29.235840                  0.461786  18.669086          1  
7  27.724017                  0.474361  44.517575          0  
8  21.032709                  0.105676  42.743013          1  
9  29.271195                  0.622292  66.017355          0

In [159]:
#dataframe= df  #pandas= pd
df = pd.read_csv(r'C:\Users\Sanket M\OneDrive\Documents\Task List\ML\Diabetes_Prediction\Diabetes_prediction.csv')
df[100:120]

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
100            1   89.947608      87.783236      24.297965  131.026245   
101            2   64.261085      54.778065      24.486385  156.921526   
102            3  108.082033      73.180534      22.352139  178.939241   
103            0   81.859837      86.225309      23.893016   58.939071   
104            2  128.582340      82.986942      22.084365  172.576924   
105            3   99.453361     105.799042      22.931480   -0.795770   
106            1  101.759376      90.011044      25.168258   56.350046   
107            2  100.425609      76.163528      23.834125   95.122942   
108            1  139.667725      86.513056      23.865728   69.229871   
109            0  109.635674      58.389866      21.898818   -6.793269   
110            3   93.177842      72.392181      22.506967  138.996039   
111            1  144.384025      68.809568      24.347502   23.236986   
112            0   46.304239      71.466039      22.476396  204.440127   
113            0  113.633814      72.228418      22.326829   69.771570   
114            1   85.868788      67.427271      23.455448   99.180121   
115            0   95.884628      62.860681      24.665047  103.704631   
116            0   89.239255      69.147820      23.537179   60.622647   
117            2  125.807362      79.074571      22.916996   84.530426   
118            2  120.273515      79.444428      23.352303   -3.714347   
119            1   75.973933      77.059817      22.517344  120.237045   

           BMI  DiabetesPedigreeFunction        Age  Diagnosis  
100  28.709938                  0.600854  60.712177          0  
101  26.771965                  0.302547  55.083229          0  
102  26.355901                  0.233320  65.835611          0  
103  22.577110                  0.676258  59.065930          0  
104  22.602384                  0.501204  59.046547          0  
105  25.964717                  0.779598  25.155442          0  
106  23.897730                  0.729617  40.555772          1  
107  29.016937                  0.530781  68.760513          0  
108  24.143602                  0.613744  40.086151          1  
109  17.341810                  0.312605  62.991327          0  
110  29.330312                  0.512884  33.168506          0  
111  27.954861                  0.779401  45.638809          0  
112  28.106090                  0.709890  29.431890          0  
113  28.171251                  0.646513  44.811147          1  
114  25.587379                  0.684661  36.128912          0  
115  29.029935                  0.790220  57.738765          0  
116  24.602069                  0.473819  67.663383          0  
117  30.692714                  0.370546  36.072400          0  
118  21.883076                  0.623624  36.888075          0  
119  19.934934                  0.193759  20.298859          0

In [160]:
df.shape

(1000, 9)

In [161]:
# Generate descriptive statistics
df.describe()

Pregnancies      Glucose  BloodPressure  SkinThickness      Insulin  \
count  1000.000000  1000.000000    1000.000000    1000.000000  1000.000000   
mean      1.771000    99.440607      72.179837      23.278316    84.582679   
std       1.354398    19.470730      13.882017       1.173807    74.872733   
min       0.000000    30.571402      31.401487      19.369987  -165.310033   
25%       1.000000    86.145927      62.795447      22.501591    35.076535   
50%       2.000000    99.458362      71.909588      23.275225    84.442232   
75%       3.000000   113.264556      82.082660      24.052022   134.267842   
max       8.000000   161.238939     110.723715      26.917654   317.701852   

               BMI  DiabetesPedigreeFunction          Age   Diagnosis  
count  1000.000000               1000.000000  1000.000000  1000.00000  
mean     25.433600                  0.449383    43.281798     0.30600  
std       3.690223                  0.199334    14.465398     0.46106  
min      13.548818                  0.100037    -0.979804     0.00000  
25%      23.022715                  0.283376    33.518451     0.00000  
50%      25.455649                  0.448219    43.634273     0.00000  
75%      27.972184                  0.619158    53.098446     1.00000  
max      36.324598                  0.799654    90.573782     1.00000

In [162]:
# Total column names
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Diagnosis'],
      dtype='object')

In [163]:
# Permanently saved column names
d = {"DiabetesPedigreeFunction":"DPF"}
df.rename(columns=d, inplace=True)

In [164]:
df.tail(5)

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
995            1  103.496355      41.059401      24.930299   43.675978   
996            1   60.714150      64.082842      24.689064  111.562745   
997            0   97.597727      64.122312      22.140339  108.138552   
998            0   66.775137      55.908797      24.885274  219.521484   
999            0   87.647268      69.111593      25.621266  134.335745   

           BMI       DPF        Age  Diagnosis  
995  25.846062  0.455884  19.905419          0  
996  19.464280  0.250560  44.421874          1  
997  22.733052  0.761463  58.949800          1  
998  31.819187  0.382877  46.928923          0  
999  31.098746  0.605828  41.785889          1

In [165]:
# Return unique values of Series object
df['Pregnancies'].unique()

array([2, 1, 3, 0, 4, 5, 6, 8], dtype=int64)

In [166]:
df['Diagnosis'].unique()

array([0, 1], dtype=int64)

In [167]:
# Type of DataFrame
type(df)

pandas.core.frame.DataFrame

In [168]:
df.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
DPF              0
Age              0
Diagnosis        0
dtype: int64

In [169]:
# Use to find the type of the unique values returned from the "Price" column in a DataFrame.
type(df['BloodPressure'].unique())

numpy.ndarray

In [191]:
# Dataset spliting into two parts, training and testing
X = df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DPF','Age']]   # Independent variables
y = df['Diagnosis']   # Target value

In [192]:
# creating traina and test dataset 100%, train_size, keep aside 20% as training data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=40)

In [193]:
model = LogisticRegression()
model.fit(X_train,y_train)

C:\Users\Sanket M\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [174]:
#test the model
y_pred = model.predict(X_test)
print(y_pred)

[0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0
 0 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0
 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1]


In [175]:
#accuracy metrics - >
print(accuracy_score(y_test,y_pred))

1.0


In [194]:
dtr_model = DecisionTreeRegressor()
dtr_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [177]:
y_pred = model.predict(X_test)
print(y_pred)

[0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0
 0 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0
 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1]


In [178]:
print(accuracy_score(y_test,y_pred))

1.0


In [195]:
rfr_model = RandomForestRegressor()

rfr_model.fit(X_train,y_train)

RandomForestRegressor()

In [180]:
y_pred = model.predict(X_test)
print(y_pred)

[0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 0 1 0 0 0 0
 0 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0
 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1]


In [181]:
print(accuracy_score(y_test,y_pred))

1.0


In [182]:
# Print confusion_matrix
conf_matrix = print(confusion_matrix(y_test,y_pred))

[[144   0]
 [  0  56]]


In [188]:
print(X.shape)

(1000, 8)


In [196]:
# Create Diabetes_Prediction.pkl file
with open(r'C:\Users\Sanket M\OneDrive\Documents\Task List\ML\Diabetes_Prediction\Diabetes_Prediction.pkl', 'wb') as f:
    pickle.dump(model, f)